MetaModels/core

- src/MetaModels/DcGeneral/Events/Table/FilterSetting/Subscriber.php
> add check for existing filters global https://github.com/MetaModels/core/issues/690

- src/MetaModels/ItemList.php
you forgot to set the current page attribute depending on the page parameter if set and integer
> fixed #744

- contao/config/event_listeners.php
- src/MetaModels/DcGeneral/Dca/Builder/Builder.php
- src/MetaModels/DcGeneral/Events/MetaModel/CreateVariantButton.php
- src/MetaModels/DcGeneral/Events/MetaModel/DuplicateModel.php
Some fixes and refactoring to get the variants working, see: https://github.com/MetaModels/core/issues/763
@discordier Can you review it as fast as possible, we need the working variants.
> Get the variants working

- src/MetaModels/Helper/ToolboxFile.php
There are a lot of file information but not the extension.
> Added extension to toolbox file

- src/MetaModels/DcGeneral/Dca/Builder/Builder.php
This pull request adds the missing sorting direction when a grouping setting is used.
> Fix sorting direction when grouping is active.

- contao/config/event_listeners.php
- src/MetaModels/DcGeneral/Events/MetaModel/CutButton.php
Implement an event listener which disables the cut button when no manual sorting is used.
> Disable cut button when no manual sorting is used.

- src/MetaModels/DcGeneral/Events/Table/FilterSetting/Subscriber.php
- src/MetaModels/DcGeneral/Events/Table/InputScreenSortGroup/Subscriber.php
Pull request provides fix for #496.
> Get correct value and avoid naming collisions.

- src/MetaModels/BackendIntegration/InputScreen/InputScreen.php
- src/MetaModels/DcGeneral/Events/BreadCrumb/BreadCrumbInputScreenCondition.php
This pull request add support for legend conditions.  They will be added to the property conditions which are in the fieldset of the legend.
Known limitation: The conditions are applied by the default used `AND` conjunction.
> Support legend conditions.

- contao/config/database.sql
- contao/dca/tl_metamodel_dca.php
- contao/dca/tl_metamodel_rendersettings.php
- src/MetaModels/BackendIntegration/InputScreen/IInputScreen.php
- src/MetaModels/BackendIntegration/InputScreen/InputScreen.php
- src/MetaModels/DcGeneral/Dca/Builder/Builder.php
- src/MetaModels/DcGeneral/Events/MetaModel/RenderItem.php
When showColumns is on, DcGeneral expects an array with the values to be returned.
Currently you have to set 
\ContaoCommunityAlliance\DcGeneral\DataDefinition\Definition\View\DefaultListingConfig::getShowColumns
to true to see an effect
> Properly render in listView (showColumns=true) mode

- src/MetaModels/DcGeneral/Dca/Builder/Builder.php
This pull requests add the select button (edit all) to the input screen for meta models. It's required to use multiple actions, implemented in contao-community-alliance/dc-general#133.
> Add select button for MetaModels.

- src/MetaModels/DcGeneral/Dca/Builder/Builder.php
> Followup #841 #827: Fix/port list view header

- src/MetaModels/DcGeneral/Events/MetaModel/PasteButton.php
This pull request provides fixed for clipboard related issues.
* Allow ModelId being `NULL`
* Only check `pid` when parent definition is given
This pull requests depends on contao-community-alliance/dc-general#151 and will increase the required version of the dc general.
> Fix clipboard related issues

- src/MetaModels/FrontendIntegration/Content/Filter.php
- src/MetaModels/FrontendIntegration/Content/FilterClearAll.php
- src/MetaModels/FrontendIntegration/Content/ModelList.php
The links are wrong and I have added the wildcard output for the Filter.
> fix content element wildcard links in the back end

- contao/dca/tl_metamodel_dcasetting_condition.php
- contao/languages/en/explain.php
- contao/languages/en/tl_metamodel_dcasetting_condition.php
Ersatz für https://github.com/MetaModels/core/pull/950
gehört zusammen mit https://github.com/MetaModels/core/pull/951
> Hotfix für #944 Ansichtsbedingungen Attribut Eingabemaske

- contao/config/config.php
siehe auch https://github.com/MetaModels/core/issues/857
> Ansichtsbedingungen für Tags

- contao/dca/tl_metamodel.php
> add missing data provider and child conditions

- contao/templates/be_dcastylepicker.html5
- contao/templates/be_detectedproblems.html5
- contao/templates/be_metamodel_full.html5
- contao/templates/be_subdca.html5
- contao/templates/be_supportscreen.html5
- contao/templates/ce_metamodel_list.html5
- contao/templates/ce_metamodel_list.xhtml
- contao/templates/metamodel_prerendered.html5
- contao/templates/metamodel_prerendered.text
- contao/templates/metamodel_prerendered.xhtml
- contao/templates/metamodel_unrendered.html5
- contao/templates/metamodel_unrendered.text
- contao/templates/metamodel_unrendered.xhtml
- contao/templates/mm_filter_clearall.html5
- contao/templates/mm_filter_clearall.xhtml
- contao/templates/mm_filter_default.html5
- contao/templates/mm_filter_default.xhtml
- contao/templates/mm_filteritem_checkbox.html5
- contao/templates/mm_filteritem_checkbox.xhtml
- contao/templates/mm_filteritem_default.html5
- contao/templates/mm_filteritem_default.xhtml
- contao/templates/mm_filteritem_linklist.html5
- contao/templates/mm_filteritem_linklist.xhtml
- contao/templates/mm_filteritem_radiobuttons.html5
- contao/templates/mm_filteritem_radiobuttons.xhtml
- contao/templates/mod_metamodel_list.html5
- contao/templates/mod_metamodel_list.xhtml
- src/MetaModels/Render/Template.php
Changes for #1045.
What blocks are relevant for the templates and which are not?
> [RFC] Add missing features for template v2

- src/MetaModels/Helper/TableManipulation.php
By add a new column or rename it, test if the column name post fix is reserved.
The is usefull for virtual column name see example by attribute_file.
See here:
https://github.com/MetaModels/attribute_file/pull/55/commits/9c557d0c64327d2a80d1838e7de7d05b23969fd4#diff-89d0bbba6af49d60355b36c86e873604R158
> Column name post fix is reserved

- src/MetaModels/FrontendIntegration/Module/Filter.php
Hotfix add wildcard to filter module
> Hotfix add BE wildcard to filter module

- contao/config/config.php
- contao/languages/de/tl_maintenance.php
- contao/languages/en/tl_maintenance.php
- src/MetaModels/BackendIntegration/BackendModuleBuilder.php
- src/MetaModels/BackendIntegration/PurgeAssets.php
> Hotfix #765 cache BE icons

- src/MetaModels/Helper/ToolboxFile.php
add file meta information at ToolboxFile
fix for https://github.com/MetaModels/attribute_file/issues/54
> add file meta information at ToolboxFile

- contao/dca/tl_module.php
Hotfix arrange module dca palette
> Hotfix arrange module DCA palette

- contao/templates/metamodel_prerendered.text
- contao/templates/metamodel_unrendered.text
update template text and delete ':' because laguage string include this https://github.com/MetaModels/core/blob/08b502234efe150003450cf01b5611b00f9ebd57/contao/languages/en/default.php#L61
> Hotfix update template text

- contao/templates/metamodel_prerendered.html5
- contao/templates/metamodel_prerendered.xhtml
- contao/templates/metamodel_unrendered.html5
- contao/templates/metamodel_unrendered.xhtml
change the second `"` inside of if-title
> hotfix templates

- contao/dca/tl_metamodel.php
hotfix issue #1188 delete unique for MM name
https://github.com/contao-community-alliance/dc-general/pull/359
> hotfix issue 1188 delete unique for MM name

- contao/dca/tl_metamodel_dca_combine.php
Hotfix change sql in DCA combine to save Anonymous
> Hotfix change sql in DCA combine to save Anonymous

- contao/dca/tl_metamodel_attribute.php
Hotfix for update to use per DCG overrrideAll
https://github.com/contao-community-alliance/dc-general/pull/359
> Hotfix for update to use per DCG overrrideAll

- contao/dca/tl_metamodel_dca_sortgroup.php
hotfix issue #1184: delete 'backendcaption' at dca_sortgroup
> hotfix issue #1184: delete 'backendcaption' at dca_sortgroup

- contao/config/autoload.php
- contao/templates/metamodel_prerendered.html5
- contao/templates/metamodel_prerendered.xhtml
- contao/templates/metamodel_unrendered.html5
- contao/templates/metamodel_unrendered.xhtml
- contao/templates/mm_actionbutton.html5
- contao/templates/mm_actionbutton.xhtml
> [RFC] Introduce pre-parsed "html" node at item actions array

- contao/assets/css/style.css
- contao/assets/css/style_src.css
- src/MetaModels/FrontendIntegration/MetaModelHybrid.php
Hotfix add more info to BE wildard string
see https://github.com/MetaModels/core/issues/269
> Hotfix add more info to BE wildard string

- src/MetaModels/DcGeneral/Data/Driver.php
- src/MetaModels/DcGeneral/Events/Table/InputScreenCondition/Subscriber.php
- src/MetaModels/IItem.php
- src/MetaModels/IMetaModel.php
- src/MetaModels/Item.php
- src/MetaModels/MetaModel.php
This pull request must merged to if DCG has the feature "uniformTime" override/edit all
> [RTM] Hotfix for edit/override all in DCG

- src/MetaModels/DcGeneral/Events/Table/FilterSetting/SubPaletteSubscriber.php
hotfix  is fixed the SubPalettesSubscriber
see #1228
> [RTM] fix SubPalettesSubscriber

- src/MetaModels/FrontendIntegration/HybridList.php
Hotfix encode email strings as contao standard
see https://github.com/MetaModels/core/issues/1233
> [RTM] Hotfix encode email strings as contao standard

- contao/dca/tl_metamodel_dcasetting_condition.php
- contao/dca/tl_metamodel_searchable_pages.php
- src/MetaModels/Attribute/IInternal.php
- src/MetaModels/BackendIntegration/PurgeAssets.php
- src/MetaModels/BackendIntegration/Support.php
- src/MetaModels/ContaoIntegration/Boot.php
- src/MetaModels/DcGeneral/Events/BreadCrumb/BreadCrumbDcaCombine.php
- src/MetaModels/DcGeneral/Events/BreadCrumb/BreadCrumbInputScreenCondition.php
- src/MetaModels/DcGeneral/Events/BreadCrumb/BreadCrumbInputScreenSortGroup.php
- src/MetaModels/DcGeneral/Events/BreadCrumb/BreadCrumbSearchablePages.php
- src/MetaModels/Dca/ContentElementModuleBase.php
- src/MetaModels/Filter/Rules/Condition/ConditionAnd.php
- src/MetaModels/Filter/Setting/IFilterSettingFactory.php
- src/MetaModels/FrontendIntegration/Content/ModelList.php
- src/MetaModels/FrontendIntegration/HybridList.php
- src/MetaModels/FrontendIntegration/Module/ModelList.php
- src/MetaModels/Render/Setting/IRenderSettingFactory.php
- src/MetaModels/Widgets/PickerWidget.php
hotfix superfluous author(s)
check travis test
> [RTM] hotfix superfluous author(s)

- src/MetaModels/Helper/ToolboxFile.php
Hotfix bottle neck #1153 ToolboxFile.php
> Hotfix bottle neck #1153 ToolboxFile.php

- contao/assets/css/style.css
- contao/assets/css/style_src.css
hotfix hide popup widget hint
hide hint until new picker is created
> [RTM] hotfix hide popup widget hint

- contao/dca/tl_metamodel_filtersetting.php
- contao/languages/en/tl_metamodel_filtersetting.php
- src/MetaModels/Filter/Setting/SimpleLookup.php
Add checkbox to enable/disable frontend widgets
Frontend filter widgets for simple lookup can now be enabled and disabled via a checkbox
> [RTM] Hotfix/2.0.7 fe filter widget

- src/CoreBundle/Contao/Hooks/AbstractContentElementAndModuleCallback.php
- src/Widgets/SubDcaWidget.php
Hotfix/subdcawidget
* fix error is value null
* fix subdcawidget table
> [RTM] Hotfix/subdcawidget

- src/CoreBundle/EventListener/DcGeneral/Table/AbstractPaletteRestrictionListener.php
> [RTM] Fix duplicate legends when starting with + sign

- src/FrontendIntegration/FrontendFilter.php
Hotfix template filter clearall
see #1284
> [RTM] Hotfix template filter clearall

- src/CoreBundle/Resources/contao/dca/tl_metamodel_dcasetting.php
expand database column to text
> hotfix translated section label

- src/Attribute/TranslatedReference.php
Small changes for a better result for large lists of ids for the translated reference
Please explain the detailed changes you made here.
Reference any issue number this pull request fixes.
> [RTM] Hotfix for a better Database performance for the translated reference

- .travis.yml
- src/CoreBundle/Controller/Backend/AbstractAddAllController.php
- src/CoreBundle/Controller/Backend/PickerWidgetController.php
- src/CoreBundle/Controller/Backend/SupportMetaModelsController.php
- src/CoreBundle/Resources/config/services.yml
- src/CoreBundle/Resources/views/Backend/be_base.html.twig
Restores Symfony 4.3 compatibility.
Fixes #1342.
> [RTM] Do not use templating service but twig service to restore Symfony 4 compat

- src/CoreBundle/Resources/public/css/supportscreen.css
- src/CoreBundle/Resources/public/scss/supportscreen.scss
> [RTM] Change css for support page

- src/Attribute/BaseSimple.php
hotfix strict mode at basesimple
see issue #1335
> [RTM] hotfix strict mode at basesimple

- src/FrontendIntegration/FrontendFilter.php
Parameters are not correct implemented here. @discordier knows more about this (he made this change) ;-)
Please explain the detailed changes you made here.
Reference any issue number this pull request fixes.
> [RTM] Update FrontendFilter.php

- build.xml
- src/CoreBundle/EventListener/DcGeneral/Table/DcaSettingCondition/PasteButtonListener.php
- src/CoreBundle/EventListener/DcGeneral/Table/DcaSettingCondition/ValueListener.php
Hotfix NOT rule at view condition
see #1365
depends on https://github.com/contao-community-alliance/dc-general/pull/517
> [RTM] Hotfix NOT rule at view condition

- src/DcGeneral/Data/Driver.php
Hotfix sorting filter values in BE panel
fix #1366
> [RTM] Hotfix sorting filter values in BE panel

- src/CoreBundle/Contao/Hooks/AbstractContentElementAndModuleCallback.php
- src/CoreBundle/Contao/Hooks/ContentElementCallback.php
Fix issue with missing DC_Table
> [RTM] Fix issue with missing DC_Table

- src/Attribute/BaseSimple.php
See #1419, #1356, #1412, #1335
> Fix for only_full_group_by

- composer.json
Add conflict with contao core 4.9.27
see https://github.com/contao/contao/pull/4233
> Add conflict with contao core 4.9.27

- src/Filter/Setting/SimpleLookup.php
> Fix code style

- src/CoreBundle/EventListener/GetSearchablePagesListener.php
ensure jumpTo page ID is integer
issue #1474
> ensure jumpTo page ID is integer

- src/Filter/FilterUrlBuilder.php
Fix URL building when page alias is index and fragment list is empty.
> Fix URL building when page alias is index and fragment list is empty.

- src/Helper/TableManipulator.php
> [RTM] Fix table helper

- src/CoreBundle/EventListener/GetSearchablePagesListener.php
Fix getSearchablePages
* cast to int - value can `null`
* pass over empty `pageDetails` - `$event->getPageDetails()` return `array`
> Fix getSearchablePages

- src/CoreBundle/Resources/contao/templates/mm_clearall_default.html5
> Fix ID for anchor jump

- composer.json
- src/CoreBundle/Contao/InsertTag/ReplaceParam.php
- src/CoreBundle/Contao/InsertTag/ResolveLanguageTag.php
- src/CoreBundle/Resources/config/filter-settings.yml
- src/CoreBundle/Resources/config/insert-tags.yml
- src/Filter/Setting/CustomSql.php
- src/InsertTag/LiteralNode.php
- src/InsertTag/Node.php
- src/InsertTag/NodeInterface.php
- src/InsertTag/NodeList.php
- src/InsertTag/Parser.php
- tests/Filter/Setting/CustomSqlTest.php
- tests/Helper/TableManipulatorTest.php
add new class to resolve iflng / ifnlng inserttags in customSql query
unittest must be adjusted!
related with #1495
> Hotfix custom sql filter iflng inserttag

- src/Filter/FilterUrl.php
> Add array as possible get parameter.

- src/CoreBundle/Resources/translations/tl_metamodel_item.de.xlf
Updated translations from transifex.
> Updated translations from transifex.

- src/CoreBundle/Resources/translations/tl_metamodel_item.de.xlf
Updated translations from transifex.tx
> Updated translations from transifex.tx
