src/MetaModels/DcGeneral/Events/Table/Attribute/Subscriber.php
The method getMetaModelByModelPid() needs as first parameter an model instance instead of the pid property
=> wrong parameter

src/MetaModels/Attribute/Base.php
The parseValue hooks looses the results of a hook if multiple hooks are registered.
=> Do not loose result of previously called hooks.

src/MetaModels/DcGeneral/Events/Table/Attribute/Subscriber.php
We have to check for existing pid in the old object, because $old is every time set.
=> fix for https://github.com/MetaModels/core/issues/758

src/MetaModels/FrontendIntegration/HybridList.php
This makes whitespaces and special characters in URL Filter parameters possible.
=> Decoding filter parameters now in HybridList

src/MetaModels/DcGeneral/Data/Driver.php, src/MetaModels/DcGeneral/Events/MetaModel/PasteButton.php
This pull request provides a solution for the missing copy feature metamodels (see #743). 
The "paste into top" feature is still missing but that's probably an issue of the dcg.
=> Fix copy of metamodels

contao/dca/tl_metamodel_dca_sortgroup.php, src/MetaModels/BackendIntegration/InputScreen/InputScreenGroupingAndSorting.php
As explained here in contao-community-alliance/dc-general#73 the grouping won't work in combination with manual sorting. This is due to the fact that MetaModels only allow sorting by one attribute.
This pull request prepares the user interface by hiding grouping option if manual sorting is activated and by disabling the grouping in the inputscreen definition.
=> Disable grouping if manuals sorting is activated

src/MetaModels/DcGeneral/Events/MetaModel/RenderItem.php
This pull requests uses the GetParentHeaderEvent of the dc general to add additional fields based on the default render setting. Its the proposed solution for #184. 
I'm not sure if there is a better way to do it (Maybe a render setting could be chosen).
**Warning** It depends on https://github.com/contao-community-alliance/dc-general/pull/129
=> Add additional header fields by the default render setting.

src/MetaModels/BackendIntegration/InputScreen/InputScreenGroupingAndSorting.php
This fixes the left sorting issue mentioned in https://github.com/contao-community-alliance/dc-general/issues/154#issuecomment-129916954.
=> Return the sorting attribute name.

src/MetaModels/IItem.php, src/MetaModels/Item.php
Introduce the `IItem::getVariantBase()` as described in #237.
Unit tests for `IItem::getVariants()`, `IItem::isVariant()`, `IItem::isVariantBase()`, `IItem::getVariantBase()` unneeded?
=> Introduce `IItem::getVariantBase()`

src/MetaModels/Attribute/IInternal.php, src/MetaModels/DcGeneral/Events/Table/RenderSetting/Subscriber.php, src/MetaModels/Item.php
This feature is useful for better work with virtual attribute.
Virtual attribute has problem if we get parse values from item.
You can see this by attribute_file by the virtual [FileOrder](https://github.com/ContaoBlackForest-archive/attribute_file/blob/32516ce6ab82aa3809c2e32185f68b4055b3f648/src/MetaModels/Attribute/File/FileOrder.php#L36).
=> Add identifier for internal attribute for exclude by some methods

contao/templates/be_dcastylepicker.html5
Hotfix DCA picker - correct the path to js and css
thx to @baumannsven for the tip to add `''` :-)
=> Hotfix DCA picker - correct the path to js and css

contao/templates/ce_metamodel_list.html5, contao/templates/ce_metamodel_list.xhtml, contao/templates/metamodel_prerendered.html5, contao/templates/metamodel_prerendered.text, contao/templates/metamodel_prerendered.xhtml, contao/templates/metamodel_unrendered.html5, contao/templates/metamodel_unrendered.text, contao/templates/metamodel_unrendered.xhtml, src/MetaModels/Item.php, src/MetaModels/ItemList.php
Add the variable createEnable to the MetaModel list template. There is no need to show the addUrl button if the table is not creatable.
See MetaModels/contao-frontend-editing#7
=> Remove the front end editing fragments from the core template and rework "actions" in the list template

src/MetaModels/Items.php
I was not able to set a custom css class per item via the `ParseItemEvent`.
=> Concatenate css classes

contao/dca/tl_metamodel_filtersetting.php, src/MetaModels/DcGeneral/Events/Table/FilterSetting/Subscriber.php
hotfix issue #1203 add all_langs option
see `preparePalettes`
https://github.com/MetaModels/core/commit/6ae958e40985b18b8c14968586ff5e7a7ed87d43
=> [RTM] hotfix issue #1203 add all_langs option

src/MetaModels/MetaModel.php
Hotfix bottle neck 2 #1153 MetaModels.php
=> Hotfix bottle neck 2 #1153 MetaModels.php

src/MetaModels/DcGeneral/Data/Driver.php, src/MetaModels/Item.php
When creating a new item and finally saving the item, neither the alias attributes nor the combined values attributes get generated.
The item gets initialized with `$arrData = []` meaning we have to initialize all attributes so that they are present in the data array. This is related to #894 and 588eddf respectively.
When `$arrData` is empty, `isAttributeSet()` returns `false` which results in no attributes get notified about a model change.
1. Using the API
```php
$item = new Item($metaModel, null);
$item->set('name', 'Test');
$item->save();
// neither alias nor combined values have been generated now
```
2. Using the Frontend Editing.
Neither alias nor combined values are generated on creation.
3. MetaModels 2.0 as well 2.1 are affected.
* We might want to add a `getEmptyValue()` to the …
=> [RTM] Initialize attributes with empty values.

src/MetaModels/Widgets/PickerWidget.php
The picker widget show warnings about missing constants  TL_ASSETS_URL and TL_FILES_URL. This PR fixes it by calling `Controller::setStaticUrls()` which defines the constants.
=> [RTM] Fix warnings in the picker widget.

src/CoreBundle/EventListener/SubSystemBootListener.php, src/CoreBundle/Resources/config/listeners.yml, src/CoreBundle/Resources/contao/config/config.php
This PR rewrites the SubSystemBoot class as registered service.
This PR fixes the error
"The "logger" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead."
I needed to inject the `logger` service because it is not public.
=> Rewrite SubSystemBoot as registered service.

src/CoreBundle/Contao/Compat/ContaoFactory.php, src/CoreBundle/Resources/config/services.yml
Session access inside a custom SQL filter e.g.
`{{param::session?name=mm_blog_post_id&default=0}}`
Throws an exception like this:
`Using $this when not in object context`
Unlike Contao\Input Contao\Session has to be instantiated by getInstance()
=> Hotfix for custom SQL filter

src/CoreBundle/Assets/IconBuilder.php, src/CoreBundle/Resources/config/services.yml
Description
In Contao 4.8 the image factory requires absolute paths (as it was only documented before), see https://github.com/contao/contao/commit/3a48a3dd0a441342121a388f014dce66ea8c4cc0. This leads to errors with the metamodels input mask. 
Disclaimer: I know that MetaModels does not officially support Contao > `^4.4`. However it would be one step closer for the upcoming LTS 4.9.
=> [RTM] Pass absolute paths to the image factory

src/ItemList.php
Error message stated the factory found a MetaModel by ID even though the error was, that it actually did not ;-)
=> [RTM] Fix error message, if a MetaModel could not be found

src/CoreBundle/Contao/Hooks/FixupUserGroupModules.php
fix Type error: Too few arguments to function tl_user_group::getModules(), 0 passed in /var/www/html/vendor/metamodels/core/src/CoreBundle/Contao/Hooks/FixupUserGroupModules.php on line 86 and exactly 1 expected
=> [RTM] Update FixupUserGroupModules.php

src/CoreBundle/Contao/Hooks/RegisterBackendNavigation.php
hotfix storage adapter for contao hook
=> [RTM] hotfix storage adapter for contao hook

src/CoreBundle/EventListener/SubSystemBootListener.php
When there has been an error checking the tables on bootup, the
exception was not being catched. Instead it broke the whole install
process due to the newly added migrations.
=> [RTM] Fix issue #1376 - catch db error on bootup

src/CoreBundle/Resources/contao/dca/tl_metamodel.php, src/CoreBundle/Resources/contao/dca/tl_metamodel_dca.php, src/CoreBundle/Resources/contao/dca/tl_metamodel_dca_sortgroup.php, src/CoreBundle/Resources/contao/dca/tl_metamodel_filter.php, src/CoreBundle/Resources/contao/dca/tl_metamodel_rendersettings.php
Some DCA fields have different max length definition in SQL and eval array. This leads for example to cutted text when saving to the database.
=> [RTM] Fix different max length definition of DCA name fields in SQL and eval array

src/CoreBundle/Resources/contao/dca/tl_metamodel_dca_sortgroup.php
implements #1430
With this PR the sortings can be manually sorted. This sort order will be used to create the sort drop down in the backend list view.
=> [RTM] Make the sorting sortable to use the order in the backend list view

src/CoreBundle/Controller/ListControllerTrait.php, src/FrontendIntegration/HybridList.php, src/ItemList.php
Fix the renamed method getObjItems to getItems and add BC layer
fix commit https://github.com/MetaModels/core/commit/fdc408c4914e6202c0362cfad3b450df445126a2#diff-e3b36620f81bc583e1ae275d828897526784d42496c0f06876a037ef9bc8f1e4
=> Fix the renamed method getObjItems to getItems and add BC layer

src/Filter/Setting/CustomSql.php
fixes the problem with strung together and nested inserttags
this should fix https://github.com/MetaModels/core/issues/880#issuecomment-1257963684
=> Hotfix custom sql filter inserttags

src/CoreBundle/Contao/Hooks/AbstractContentElementAndModuleCallback.php, src/CoreBundle/Resources/contao/dca/tl_content.php, src/CoreBundle/Resources/contao/dca/tl_module.php, src/CoreBundle/Resources/contao/languages/de/tl_content.php, src/CoreBundle/Resources/contao/languages/de/tl_module.php, src/CoreBundle/Resources/contao/languages/en/tl_content.php, src/CoreBundle/Resources/contao/languages/en/tl_module.php, src/MetaModel.php
Fix list of attributes in MM List as CE and Module
=> Fix list of attributes in MM List as CE and Module

src/CoreBundle/Contao/Hooks/ContentElementCallback.php, src/CoreBundle/Contao/Hooks/FilterContentElementCallback.php, src/CoreBundle/Contao/Hooks/FilterModuleCallback.php, src/CoreBundle/Contao/Hooks/ModuleCallback.php, src/CoreBundle/Resources/config/hooks.yml, src/CoreBundle/Resources/contao/dca/tl_content.php, src/CoreBundle/Resources/contao/dca/tl_module.php, src/FrontendIntegration/FrontendFilter.php
see https://github.com/MetaModels/core/issues/345
=> Add preset for FE filter

src/CoreBundle/Contao/Hooks/ContentElementCallback.php, src/CoreBundle/Contao/Hooks/FilterContentElementCallback.php
Fix rights check for non-admin user
=> Fix rights check for non-admin user
